Add new Grafana dashboards: Aggregated Reports, Project Insights, and…
epam/ai-dial-analytics-realtime pull request #82
Opened 2024-12-11 15:21 UTC by davidpepm

### Description

This pull request adds three new Grafana dashboards to the **AI DIAL Realtime Analytics** project as part of the requirements outlined in [[Issue #62](https://github.com/epam/ai-dial-analytics-realtime/issues/62)](https://github.com/epam/ai-dial-analytics-realtime/issues/62). 

The new dashboards are as follows:
1. **DIAL Analytics Aggregated Report**: Focuses on aggregated metrics, providing insights derived from pre-aggregated data for performance optimization.
2. **DIAL Project Insights**: Offers detailed analytics at the project level, enabling better monitoring and understanding of project-specific metrics.
3. **DIAL User Insights**: Provides user-level analytics to track and analyze individual user behavior and contributions.

### Dependencies

This PR is dependent on the following pull request in the **InfluxData Helm Charts** repository:
- [[PR #692](https://github.com/influxdata/helm-charts/pull/692)](https://github.com/influxdata/helm-charts/pull/692): Adds the required buckets and tasks to support the new Grafana dashboards.  
This pull request must be merged before this one can be fully functional.

### Changes in this PR

1. Added three new dashboard JSON files under the **Grafana Dashboards** directory:
   - `DIAL Analytics Agg.json`
   - `DIAL Project Insights.json`
   - `DIAL User Insights.json`
2. Updated the project documentation (`README.md`) to reflect the addition of these dashboards.

### Testing

Please ensure the following:
- All pre-requisite dependencies from the InfluxDB setup are correctly deployed and functional.
- Grafana is configured to load these new dashboards and displays the expected data as visualized.

### Issue Reference

Closes [[Issue #62](https://github.com/epam/ai-dial-analytics-realtime/issues/62)](https://github.com/epam/ai-dial-analytics-realtime/issues/62) once merged.  

### Notes

These dashboards rely on aggregated data for improved performance. Ensure the required changes in the InfluxDB Helm Chart repository have been deployed and tested before integrating this PR.

2024-12-11 15:22 UTC, ai-dial-actions commented
Hey there and thank you for opening this pull request! 👋🏼

We require pull request titles to follow the [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/) and it looks like your proposed title needs to be adjusted.

Details:

```
No release type found in pull request title "Add new Grafana dashboards: Aggregated Reports, Project Insights, and…". Add a prefix to indicate what kind of release this pull request corresponds to. For reference, see https://www.conventionalcommits.org/

Available types:
 - fix
 - hotfix
 - feat
 - feature
 - chore
```
<!-- Sticky Pull Request Commentpr-title-lint-error -->

2025-03-25 07:24 UTC, davidpepm commented
Documentation and setup instructions are added for enabling the aggregated Grafana dashboards in the AI DIAL Realtime Analytics project.

✅ What's included:
New influxdb/README.md
Contains detailed steps for:

Manually creating required InfluxDB buckets (default_agg_*)

Importing scheduled Flux tasks (aggregate_data, monthly_agg) using the Influx CLI

Explains bucket purpose, retention policy, and usage in dashboards

Updated root README.md

Improved the Aggregated Dashboards (Optional) section

References the influxdb/README.md for setup details

 Note:
These setup steps are manual and must be performed via CLI or UI. Helm does not provision these automatically.

Let me know if any clarification is needed or if you'd prefer to automate some of this in the future.

2025-03-25 14:12 UTC, alexey-ban requested changes

2025-03-25 14:12 UTC, alexey-ban commented on influxdb/README.md
> +> ⚠️ These steps are **not automated by the Helm chart** and must be performed manually using the InfluxDB CLI or UI.
This documentation does not impose Influx installation methods, only its presence is required. I believe removing the mention of Helm is necessary.

2025-03-25 14:12 UTC, alexey-ban commented on influxdb/README.md
> +### 📦 Task Files
Which data bucket is required for task execution? Is it possible to assign a different bucket name?

2025-03-25 14:12 UTC, alexey-ban commented on influxdb/README.md
> +| `aggregate_data`  | Every 6 hours       | Performs 6-hour rolling aggregations       |
Is it possible to change this schedule? What will it affect?

2025-03-25 14:18 UTC, davidpepm commented on influxdb/README.md
> +| `aggregate_data`  | Every 6 hours       | Performs 6-hour rolling aggregations       |
6hours was a sweet spot for querying the default bucket without cause any overload.h

2025-03-25 14:23 UTC, davidpepm commented on influxdb/README.md
> +> ⚠️ These steps are **not automated by the Helm chart** and must be performed manually using the InfluxDB CLI or UI.
removed

2025-03-25 14:28 UTC, davidpepm commented on influxdb/README.md
> +### 📦 Task Files
The table is extended with the list of buckets that are used.
The names of the buckets represents if they are aggregated on non aggregated bucket and their specialty. eg.: kpi / chat_id/stats focused

2025-03-25 14:36 UTC, alexey-ban commented on influxdb/README.md
> +### 📦 Task Files
I don't see the purpose of the 'default' bucket in the document.

2025-03-25 15:20 UTC, davidpepm commented on influxdb/README.md
> +### 📦 Task Files
Updated the InfluxDB README:
Clarified that default is the main source bucket for raw analytics data
Split the task table into Source and Target Buckets

2025-03-26 12:06 UTC, alexey-ban approved these changes

2025-03-26 12:35 UTC, merged